services:

  store_catalog:
    build: .
    restart: always
    depends_on:
      - typesense
    environment:
      - TYPESENSE_API_KEY=abcd
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_PROTOCOL=http
    ports:
      - 80:8000


  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=abcd --enable-cors'
